### ISSUE TITLE
Components naming

### ISSUE THREAD

**Issue by lucasfernog** [mesqueeb/quasar-app-extension-draggable#3]
Will this extension work only for horizontal dragging? If not, I think the component names should be QDraggableContainer and QDraggableItem, something like that... "row" implies some behavior that may not be true.

**Comment by mesqueeb** [comment]
Hi! Currently i made rows for horizontal dragging. I’m thinking of adding free directional dragging later but will have to probably rewrite everything for that. So I’ll keep the rows to just horizontal and add free drag through an “item” component later. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@lucasfernog If you're in a rush to implement this in your app, look at [vue-nestable](https://rhwilr.github.io/vue-nestable/).
I never tried but it looks almost the same as my component, but you can also drag across different lists. 

This is exactly something I want to implement once for "trello" or "kanban" like apps. (if you know what I mean)

But it will probably take more time. 😄 

Also feel free to contribute to the code via PR's! I can help you understand the current codebase if you're willing to help!!! 🐯

**Comment by lucasfernog** [comment]
No problem, thanks for this awesome extension

**Comment by lucasfernog** [comment]
If I find some time I will check the codebase. However, I have some stuff to do in Quasar core.
