### ISSUE TITLE
indent / unindent via touch

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/quasar-app-extension-draggable#4]
I will make it possible for a swipe on a row to right or left to indent / unindent.

@qyloxe

**Comment by mesqueeb** [comment]
@qyloxe
Done!
check out the latest demo page now with swipe right/left to indent/unindent! ❤️
https://quasar-app-extension-draggable.netlify.com/#/

<sub>--<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>

**Comment by qyloxe** [comment]
Looks cool!

One situation (all with mouse, default settings - F5):

1. select Introject
2. drag before Nova
3. drag left Introject. Nova is selected, too.
4. drag Oracles right (without select).
5. Oracles disappears.

Effect is like this:
![image](https://user-images.githubusercontent.com/467508/57568976-13ea2200-73ef-11e9-92ea-37711fc58fd1.png)
