### ISSUE TITLE
[FEATURE] little UX improvement

### ISSUE THREAD

**Issue by qyloxe** [mesqueeb/quasar-app-extension-draggable#5]
Can we have also Alt Right==Indent, Alt Left==Unindent?

Why? Because when moving items with alt up, down, it is very convenient to use also right and left arrow.

**Comment by mesqueeb** [comment]
@qyloxe on it!!
# ⏱

**Comment by mesqueeb** [comment]
@qyloxe aaaand done
# 🎢

Check the new demo with alt+left/right to indent/unindent:
https://quasar-app-extension-draggable.netlify.com/#/

<sub>--<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>

**Comment by qyloxe** [comment]
Awesome! I must say, it is quite satisfying to just press alt and move something by cursors :-)
